[package]
name = "auth-api"
version = "0.1.0"
authors = ["Gunnar Sv Sigurbjörnsson <gunnar.sigurbjornsson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
r2d2_postgres = "0.18.0"